require.config({
    baseUrl: 'app',
    paths: {
        'jquery': '../lib/jquery/jquery.min',
        'angularAMD': '../lib/angularAMD/angularAMD.min', 
        'ngload': '../lib/angularAMD/ngload.min', 
        'ui-router': '../lib/angular-ui-router/dist/angular-ui-router',
        'angular': '../lib/angular/angular',
        'ngAnimate':"../lib/angular-animate/angular-animate.min",
        'ngSanitize':'../lib/angular-sanitize/angular-sanitize.min',
        'lazy-image': '../lib/angular-lazy-image/lazy-image',
        'file-upload': '../lib/ng-file-upload/ng-file-upload.min',
        'ngFile':'../lib/ng-file-upload/ng-file-upload-shim.min',
        'ui-bootstrap': '../lib/angular-bootstrap/ui-bootstrap-tpls',
        'bindonce':'../lib/angular-bindonce/bindonce.min',
        'localStorageUsage':'../lib/ng-localStorage/localStorageUsage',
        'angular-loading':'../lib/angular-loading/angular-loading.min',
        'spinjs':'../lib/spinjs/spin',
        'angular-toastr':'../lib/angular-toastr/dist/angular-toastr.tpls.min',
        'angular-confirm':'../lib/angular-bootstrap-confirm/dist/angular-bootstrap-confirm.min',
        'dateTimePicker':"../lib/datetime-picker/dist/datetime-picker",
        'angular-zh-cn':"../lib/angular-locale-zh-cn-master/angular-locale_zh-cn",
         //simditor编译器 start
        'simple-module':'../lib/angular-simditor/simple-module/lib/module',
        'simple-hotkeys':'../lib/angular-simditor/simple-hotkeys/lib/hotkeys',
        'simple-uploader':'../lib/angular-simditor/simple-uploader/lib/uploader',
        'simditor':'../lib/angular-simditor/simditor/lib/simditor',
        'beautify':'../lib/angular-simditor/js-beautify/js/lib/beautify',
        'beautify-css':'../lib/angular-simditor/js-beautify/js/lib/beautify-css',
        'html_beautify':'../lib/angular-simditor/js-beautify/js/lib/beautify-html',
        'simditor-html':'../lib/angular-simditor/simditor-html/lib/simditor-html',
        'angular-simditor':'../lib/angular-simditor/angular-simditor'
        //simditor编译器 end
    },
    shim: {
        'ui-bootstrap': ['angular'],
        'ui-router': ['angular'],
        'ngAnimate': ['angular'],
        'ngSanitize': ['angular'],
        'angularAMD':['angular'],
        'file-upload': ['angular'],
        'ngFile': ['angular'],
        "angular": { exports: "angular" },
        'lazy-image': ['angular'],
        'bindonce': ['angular'],
        'localStorageUsage':['angular'],
        'angular-loading':['angular'],
        'spinjs':['angular'],
        'angular-toastr':['angular'],
        'angular-confirm':['angular'],
        'dateTimePicker':['angular','ui-bootstrap'],
        'angular-zh-cn':['angular'],
        //simditor编译器 start
        'simple-module':['jquery'],
        'simple-hotkeys':['jquery','simple-module'],
        'simple-uploader':['jquery','simple-module'],
        'simditor':['jquery','simple-module','simple-hotkeys','simple-uploader'],
        'simditor-html':['jquery','simditor','html_beautify'],
        'angular-simditor':['angular']
        //simditor编译器 end
    },
    deps: ['app']
});
